### ISSUE TITLE
create a basic wireframe of the dashboard

### ISSUE THREAD

**Issue by yanpelov** [chingu-voyages/v16-geckos-team-02#1]

**Comment by lily-law** [comment]
![dashboard-wireframe.png](https://images.zenhubusercontent.com/5e397fb29920ec321a6296ee/ca0345b9-f6c3-4fe1-be58-28e842b0a6df)

**Comment by lily-law** [comment]
![dashboard-wireframe (1).png](https://images.zenhubusercontent.com/5e397fb29920ec321a6296ee/87a30367-d4a3-4764-8138-b85c9847cc44)

**Comment by yanpelov** [comment]
I am a little confused with the diagram as it seems to combine object-oriented representation and algorithm workflow. 
 
I would suggest maybe separating the diagram into 2:

1. one that summarizes all the object/components and describes their attributes, methods, and relations with other components. something like this: https://stackabuse.s3.amazonaws.com/media/object-oriented-design-principles-in-java.png

2. another diagram that describes the general logic and flow of the dashboard and the state machine behind it, something like this:
http://www.bibiesse.org/digitctionary/FIG/ALGOR.gif

Anyway, you are awesome! It's one of the hardest things to figure out. I believe that if we invest in the software design and architecture, before writing the first line of code, it would return itself later, as everything could become much clearer for everyone and easier to implement.

**Comment by lily-law** [comment]
I can see what you mean now, thank you :D I'm working on version 2 now.

**Comment by lily-law** [comment]
![dashboard-wireframe (2).png](https://images.zenhubusercontent.com/5e397fb29920ec321a6296ee/2ebf2283-3c1f-4e1c-83b0-aad5370fa71c)

**Comment by yanpelov** [comment]
Hi Lily,

Few questions, if you could elaborate:
1. What Status stands for?
2. Why shouldn't all of the widgets be sticky (e.g. clock)?

Btw, I created a google docs summary/pseudo code - based on your great work!
https://docs.google.com/document/d/1u3eXvqZFGe2EUh-oCsIZ6V9GOr8omd7Qr2F5lTQKcDk/edit?usp=sharing

**Comment by lily-law** [comment]
Hi Yan, 

Status is to indicate that the widget will periodically check and compare or subscribe to an API for updates and make some sort of notification when it's data changes.
Sticky would start as widgets with a text input and when the user enters text it will self assign to being a date/link/image/else text. If a link it can try to fetch a snippet/preview else it could default to just an editable title + link (will try to make that clearer on the prototype design soon.
Clock will start just as it is with a default UTC and like all the widgets an editable title input.

Nice the summary/pseudo code will be useful for all of us to work out what we're actually going to be doing :D

**Comment by lily-law** [comment]
I like the Preset Roulette Bar point, I hadn't though of it being used for presets. But it makes a lot of sense to double up as presets and saved user 'workspaces'

**Comment by lily-law** [comment]
So I think yanpelov's google doc is looking pretty good, have a look and see if you all think we've this issue covered now
