### ISSUE TITLE
Mockup design 

### ISSUE THREAD

**Issue by lily-law** [chingu-voyages/v16-geckos-team-02#16]

**Comment by zsigil** [comment]
https://drive.google.com/file/d/1eyNnamqyNw6qzVMoKfjJ2EcPcTq5hMii/view?usp=sharing

![Landingpage.png](https://images.zenhubusercontent.com/5e3984a1446c5bd71fe31d8d/ca17fd60-2806-4081-8fd8-48163b9b1551)

**Comment by zsigil** [comment]
https://drive.google.com/file/d/1tTGW6OJL37d2UdO35Epx3LCn255PjFYM/view?usp=sharing

![UserConfig.png](https://images.zenhubusercontent.com/5e3984a1446c5bd71fe31d8d/837044a8-a40e-4e3c-9635-a8e5e4340262)

**Comment by zsigil** [comment]
https://drive.google.com/file/d/1bGqEYahUXgwP8YN3AXqgV57l_hj-MarP/view?usp=sharing

![TODO.png](https://images.zenhubusercontent.com/5e3984a1446c5bd71fe31d8d/c896de3e-9a96-492b-a9d2-1dda8cc512ef)

**Comment by lily-law** [comment]
![mockup1.png](https://images.zenhubusercontent.com/5e397fb29920ec321a6296ee/a68483c6-2550-466e-bc85-39aa6c7fa3ee)

Maybe keep it simple and have everything on the same page/space?
I've not added other views yet, but the menus would just be like select elements and deleting items you'd activate with the bin icon and X's would show. What do you think?

**Comment by yanpelov** [comment]
Lily I really liked the mockup you suggested, looks super clear and friendly (UX wise)!

**Comment by yanpelov** [comment]
btw, sticky image could be a photo that we can grab from unsplash or from a personal album in google photos, and every day the photo changes.

and for sticky text we could grab inspirational quotes from some api

**Comment by lily-law** [comment]
Awesome, I'll touch it up and add a link here to the XD prototype soon. Thank you zsigil for getting this started. Sorry I assigned you for this without finding out if it's your sort of thing!

**Comment by lily-law** [comment]
[Mockup in Adobe XD](https://xd.adobe.com/view/9aac29cf-3156-4cca-7fa8-f2eaf750a8ad-ec9d/)

You can click on buttons to see view with different menus

**Comment by yanpelov** [comment]
I really liked the mockup - added few notes in the adobe xd link you shared. 
nice work!

**Comment by lily-law** [comment]
Okay updated maybe a little clearer to see how it would work... https://xd.adobe.com/view/9aac29cf-3156-4cca-7fa8-f2eaf750a8ad-ec9d/

**Comment by yanpelov** [comment]
Perfect, i really like it
