### ISSUE TITLE
Style/Dash

### ISSUE THREAD

**Issue by lily-law** [chingu-voyages/v16-geckos-team-02#24]
A place/grid for our widgets 

use: [Svelte grid](https://svelte-grid.now.sh/usage)

~Points to consider: ~
~- will need to display widgets in a grid/flexbox and at some point we'll need the ability to assign widgets a position~
~## [flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/)~
~### pros~
~- positioning: if using flexbox widget positioning can be set simply by filling empty spaces with placeholders and appending widget style with an [order property](https://www.w3schools.com/cssref/css3_pr_order.asp) ~
~- expanding dash space: flexbox is ideal for adding more items~
~### cons ~
~- managing empty slot spaces on different sized devices will be hacky. For example when on small screen each row might only have 1-2 columns which means empty slots will need to be reduced/resized so there wont be massive gaps to scroll to next widget~
~- getting an item to use multiple rows is not possible so to achieve this we'd need to wrap elements in sub inline flexboxes which is hacky ~
~## [grid](https://css-tricks.com/snippets/css/complete-guide-grid/)~
~### pros ~
~- total control over how much room each widget can take~
~- no need for empty/placeholder slots ~
~- cleaner dom~
~### cons~
~- a little more tricky to work out how to use dynamically ~
~- we'll need to find a way of appending properties to widgets to change where they're positioned while still being able to auto expand the dash space/vertical scroll area~

~Recommend: find a way to do it with grids~

**Comment by evgeshabond** [comment]
Hey. I am going to read docs and implement this feature in our App.svelte
https://xd.adobe.com/view/9aac29cf-3156-4cca-7fa8-f2eaf750a8ad-ec9d/
Am i right, that it is our last design version of our app?

**Comment by lily-law** [comment]
Hey, that's cool, the design is a mock up just to give a feel of what our final feature rich app might look like.  If we build a prototype we can then work out a better final design.
