### ISSUE TITLE
Feature/DashNav

### ISSUE THREAD

**Issue by lily-law** [chingu-voyages/v16-geckos-team-02#25]
This will be a sibling element to Dash and will let users know which dash they are using
### needed 
  - editable title
### wanted for later
  - create new dashboards 
  - delete dashboards
  - roulette Bar styling
  - dashboard presets
  - create user preset
  - delete user preset
  - swipe left/right to change dash/preset

**Comment by zsigil** [comment]
#### smaller issues

* limiting character number for dashTitle
