### ISSUE TITLE
Decide styling

### ISSUE THREAD

**Issue by zsigil** [chingu-voyages/v16-geckos-team-02#28]
CSS / SCSS preprocessors
UI Framework?
Grid?

**Comment by zsigil** [comment]
#### Things to consider:

* if we decide on using a UI framework (eg for dialogs) , there are not much frameworks to choose from (svelte material ui, basically, I have not found any more like this for svelte)
* if we do not use a framework, if we want dialogs, nice inputs,mobile drawers,  etc it will take more css/js (but we do not necessarily have to use dialogs, of course)
* same with grid (if we use eg Bootstrap/materialize css , we do not have to write one ourselves) ---css grid - anyone ever used that ? (I mean this one: https://css-tricks.com/snippets/css/complete-guide-grid/ , not the bootstrap-style)

##### global css
in svelte, all styles in the components are scoped, so we would practically need a global css
* css/scss? we will need preprocessors for those (should those be configured in the development/master branch directly?)

**Comment by yanpelov** [comment]
Regarding the last question, as far as I know, if we plan to use scss, we just have to add gulp or webpack and let it compile scss to css. 

I think, that if we decide to add gulp or webpack, we will need to add it to package.json (which is present in all branches) and then we can locally run npm install to install them. then we would have to add a gulp file (or it's webpack equivalent) which would run the scss to css compile task. the gulpfile can be pushed as well.
scss files can be kept in the src folder and the compiled css files in the public folder.

Also I saw this option:
https://daveceddia.com/svelte-with-sass-in-vscode/
though I am not sure if it has a watch option (one that refresh upon every change in scss)

What do you think?

**Comment by zsigil** [comment]
I guess in svelte, Rollup does the same work as Webpack (or should do, or something like that)
I think that option in the link would be fine, if it also works for global css/scss

**Comment by evgeshabond** [comment]
1. Ui. Lets use Tools build in Svelte. I think it will be ok for our Tasks.
3. Css library. So we have 2 variants: Bootstrap and Materialize. I have use none of them. But i think Bootstrap worth it, cause it is more popular.
2. Sass. Svelte uses Rollup (webpack analog) by default. So if we decide to use scss, we need to find sass-loader for rollup. But! For what do we need Sass? We have already global library (Bootstrap for example). The best features of Sass are variables (global colors and themes for ex) and class nesting. Both of these features are useless, because of Css Scoping in Svelte. May be we should use only Vanilla Css, so we have 1 Problem less.

**Comment by zsigil** [comment]
yeah, we could easily drop the scss part  for this app

but I still think the UI framework would be a big help

**Comment by lily-law** [comment]
It looks like in Svelte you can global style with :global https://svelte.dev/docs#style
What sort of UI's do you have in mind? I was thinking to keep it simple as well as feel more modern we could avoid complicating things with popups and modals as much as possible and have the UI built right into the displayed components. This should make things feel more like a web app as opposed to a website.

**Comment by zsigil** [comment]
okay-dokay, no modals then :D
