### ISSUE TITLE
setup/skeleton-sandbox (branch)

### ISSUE THREAD

**Issue by lily-law** [chingu-voyages/v16-geckos-team-02#29]
The idea of this branch is that if anyone wonders how something might work they can test/try in this branch and it'll make working out how best we could do things more practical
we can also use it to base the actual skeleton for the prototype once we've worked out how we're going to do it

**Comment by yanpelov** [comment]
I think that we can use the development branch for this purpose. If it's only something we want to test locally, we can create a local branch that is forked from the development and use that rather then creating on the remote..
If we do want it  run on the development branch. We can PR it in, and it will be reflected on the remote. what do you think? If it's unclear i can maybe give an example.

**Comment by lily-law** [comment]
Yes I understand, I think I was thinking we could use this branch to share some ideas of what might work without polluting the development branch history.

**Comment by yanpelov** [comment]
Ok cool :)

**Comment by yanpelov** [comment]
Do you want that we deploy it as well or retarget netlify from development branch to this branch?

**Comment by lily-law** [comment]
I'm thinking it's fine to just pull updates and run locally, we won't have it for long as we'll start on the actual prototype this coming week which we'll merge into development

**Comment by yanpelov** [comment]
👍
