### ISSUE TITLE
Bug/dataStore-has-no-persistence 

### ISSUE THREAD

**Issue by lily-law** [chingu-voyages/v16-geckos-team-02#40]
Wooops so dataStore.js currently get's imported by each component that needs it. Problem is the dashboards Map (where all the data resides) lives in dataStore.js so every time we import we're making a new version. 
So we need to find a way to store dashboards Map persistently else where or change from importing to props or maybe [sveltes context api](https://svelte.dev/tutorial/context-api) ?

**Comment by zsigil** [comment]
do we have to use Map? why not just a simple array, using id-s? wouldn't that work?

**Comment by yanpelov** [comment]
Seems like a singleton pattern is needed here, one instance of map that can be used in multipile components without recreating it. I will try to figure it out, once I'll start working on it

**Comment by lily-law** [comment]
We don't have to use Maps but they're recommended for ["frequent additions and removals of key-value pairs."](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map)

**Comment by lily-law** [comment]
yanpelov, did you want this one? add yourself to the assignees to any you want otherwise I'm might steal them :D

**Comment by yanpelov** [comment]
ok, I will take it as it's seems to be part of the data store. I might contact you to consult about it.

**Comment by lily-law** [comment]
Wopps, so turns out it's persisting just fine, it's just that the Dash component doesn't yet subscribe to new widgets being added.
