### ISSUE TITLE
Setup/app-skeleton

### ISSUE THREAD

**Issue by yanpelov** [chingu-voyages/v16-geckos-team-02#6]
Create each file with imports (components, dependencies...) and a TODO comment where appropriate, using a folder structure that you feel keeps things tidy.

**Comment by lily-law** [comment]
Okies so I've published the setup/app-skeleton branch please have a look, run it to see if it works and all looks good, if so we can merge to development. 
As a rule it might be better if no one is allowed to merge their own pull request.

If you're wondering why I've removed/changed stuff from the sandbox it's to try and make this cleaner. Please avoid wrapping components in div elements for styling. When adding styles within the svelte files you don't need to add class names, they're generated on build.

**Comment by lily-law** [comment]
I've removed the input bindings and stores we had in sandbox for the moment and propose we change implementation to work like this: 
- every component that needs bind access to the store get's its own get function in dataStore.js (i.e. getWidget = ref => getActiveDash().widgets[ref]) 
- dashes and widgets within dataStore will exist in Maps each with a Symbol/unique id as a key. 
- we'll create a new svelte store for each input within the Maps
This way we can pass the ref to any component so it can find where to bind to the correct store

**Comment by yanpelov** [comment]
Could you please elaborate on the dataStore/Maps etc? I think it would be best to talk about it in the team meeting, just to explain the implementation, maybe with screen share :)

**Comment by lily-law** [comment]
[Maps](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) is just so we can easily iterate key: value lists. Generating each dash and widget a set of stores with a reference id will mean it's easy to then retrieve from the store, and this way if we make get functions for dash and widgets we can retrieve/bind to the data directly in the component that needs the data. 
The dataStore.js Setup/app-skeleton sort of describes this with a primitive implementation
