### ISSUE TITLE
Create a work gantt

### ISSUE THREAD

**Issue by yanpelov** [chingu-voyages/v16-geckos-team-02#9]

**Comment by lily-law** [comment]
Checkout the Roadmap feature on here/zenhub

**Comment by yanpelov** [comment]
You are right, roadmap does seem to fit for this purpose. Do you think we can insert future sprints as well to the roadmap?

**Comment by lily-law** [comment]
I could only see how to add epics to it, but I'll have another look, if not we could just make epics for the sprints

**Comment by lily-law** [comment]
I've created loosely planned epics to use in the Roadmap on here.
